ALTER TYPE "BookingStatus" RENAME VALUE 'CONFIRMED' TO 'ACCEPTED';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'STARTED';

ALTER TABLE "bookings"
ADD COLUMN "userLatitude" DOUBLE PRECISION,
ADD COLUMN "userLongitude" DOUBLE PRECISION;

